patch uClinux-dist-20080808-20090112.patch.gz

diff --git a/uClinux-dist/openswan/programs/setup/setup.in b/uClinux-dist/openswan/programs/setup/setup.in
--- a/uClinux-dist/openswan/programs/setup/setup.in
+++ b/uClinux-dist/openswan/programs/setup/setup.in
@@ -13,7 +13,6 @@
 # or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
 # for more details.
 #
-# RCSID $Id: setup.in,v 1.122.6.8 2007-11-07 02:36:05 paul Exp $
 #
 # ipsec         init.d script for starting and stopping
 #               the IPsec security subsystem (KLIPS and Pluto).
@@ -87,7 +86,13 @@ done
 # Pick up IPsec configuration (until we have done this, successfully, we
 # do not know where errors should go, hence the explicit "daemon.error"s.)
 # Note the "--export", which exports the variables created.
-eval `ipsec _confread $config --optional --varprefix IPSEC --export --type config setup`
+variables=`ipsec addconn $config --varprefix IPSEC --configsetup`
+if [ $? != 0 ]
+then
+    echo "Failed to parse config setup portion of ipsec.conf"
+    exit $?
+fi
+eval $variables
 
 if test " $IPSEC_confreadstatus" != " "
 then
@@ -112,78 +117,84 @@ export IPSECsyslog
 umask 022
 
 mkdir -p /var/run/pluto
-mkdir -p /var/lock/subsys
 
+RETVAL=0
 
-# do it
-case "$1" in
-  start|--start|stop|--stop|_autostop|_autostart)
+start_stop() {
+	# remove for: @cygwin_START@ 
 	# portable way for checking for root
 	if [ ! -w / ]
 	then
-		
 		echo "permission denied (must be superuser)" |
 			logger -s -p $IPSECsyslog -t ipsec_setup 2>&1
 		exit 1
 	fi
-	# make sure all directories exist (mostly for openwrt)
-	if [ ! -d /var/run/pluto ]
-	then
-		mkdir -p /var/run/pluto
-	fi
-	if [ ! -d /var/lock/subsys ]
-	then
-		mkdir -p /var/lock/subsys
-	fi
-	tmp=/var/run/pluto/ipsec_setup.st
-	outtmp=/var/run/pluto/ipsec_setup.out
+	# remove for: @cygwin_END@
 	(
-		ipsec _realsetup $1
-		echo "$?" >$tmp
-	) > ${outtmp} 2>&1
-	st=$?
-	if test -f $tmp
-	then
-		st=`cat $tmp`
-		rm -f $tmp
-	fi
-	if [ -f ${outtmp} ]; then
-		cat ${outtmp} | logger -s -p $IPSECsyslog -t ipsec_setup 2>&1
-		rm -f ${outtmp}
-	fi
-	exit $st
+	ipsec _realsetup $1
+	RETVAL="$?" 
+	) 2>&1 | logger -s -p $IPSECsyslog -t ipsec_setup 2>&1  
+
+	return $RETVAL
+}
+
+
+restart_reload() {
+	$0 $IPSEC_setupflags stop
+	$0 $IPSEC_setupflags start
+}
+
+
+autorestart() {
+	$0 $IPSEC_setupflags _autostop
+	$0 $IPSEC_setupflags _autostart
+}
+
+version() {
+	ipsec version
+	RETVAL=$?
+	return $RETVAL
+}
+
+
+show_help() {
+	echo "Usage: $me [ --showonly ] {--start|--stop|--restart}"
+	echo "       $me --status"
+	RETVAL=0
+	return $RETVAL
+}
+
+# do it
+case "$1" in
+  start|--start|stop|--stop|_autostop|_autostart)
+	start_stop $1
 	;;
 
   restart|--restart|force-reload)
-	$0 $IPSEC_setupflags stop
-	$0 $IPSEC_setupflags start
+	restart_reload
 	;;
 
   _autorestart)			# for internal use only
-	$0 $IPSEC_setupflags _autostop
-	$0 $IPSEC_setupflags _autostart
+	autorestart
 	;;
 
   status|--status)
 	ipsec _realsetup $1
-	exit
+	RETVAL=$?
 	;;
 
-  --version)
-	echo "$me $IPSEC_VERSION"
-	exit 0
+  version|--version)
+	version
 	;;
 
-  --help)
-	echo "Usage: $me [ --showonly ] {--start|--stop|--restart}"
-	echo "       $me --status"
-	exit 0
+  help|--help)
+	show_help
 	;;
 
   *)
 	echo "Usage: $me [ --showonly ] {--start|--stop|--restart}"
 	echo "       $me --status"
-	exit 2
+	RETVAL=2
 esac
 
-exit 0
+exit $RETVAL
diff --git a/uClinux-dist/user/clamav/clamav-milter/Makefile.in b/uClinux-dist/user/clamav/clamav-milter/Makefile.in
--- a/uClinux-dist/user/clamav/clamav-milter/Makefile.in
+++ b/uClinux-dist/user/clamav/clamav-milter/Makefile.in
@@ -57,7 +57,9 @@ subdir = clamav-milter
 DIST_COMMON = $(srcdir)/Makefile.am $(srcdir)/Makefile.in INSTALL
 ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
 am__aclocal_m4_deps = $(top_srcdir)/m4/acinclude.m4 \
-	$(top_srcdir)/m4/lib-link.m4 $(top_srcdir)/m4/lib-prefix.m4 \
+	$(top_srcdir)/m4/fdpassing.m4 $(top_srcdir)/m4/lib-link.m4 \
+	$(top_srcdir)/m4/lib-prefix.m4 \
+	$(top_srcdir)/m4/mmap_private.m4 $(top_srcdir)/m4/resolv.m4 \
 	$(top_srcdir)/configure.in
 am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
 	$(ACLOCAL_M4)
@@ -112,7 +114,9 @@ AWK = @AWK@
 CC = @CC@
 CCDEPMODE = @CCDEPMODE@
 CFGDIR = @CFGDIR@
-CFLAGS = @CFLAGS@
+CFLAGS = `echo "@CFLAGS@" | sed -e 's/-Werror[^-]//'`
+CHECK_CFLAGS = @CHECK_CFLAGS@
+CHECK_LIBS = @CHECK_LIBS@
 CLAMAVGROUP = @CLAMAVGROUP@
 CLAMAVUSER = @CLAMAVUSER@
 CLAMAV_MILTER_LIBS = @CLAMAV_MILTER_LIBS@
@@ -131,7 +135,10 @@ ECHO_T = @ECHO_T@
 EGREP = @EGREP@
 EXEEXT = @EXEEXT@
 FRESHCLAM_LIBS = @FRESHCLAM_LIBS@
+GCOV = @GCOV@
+GENHTML = @GENHTML@
 GETENT = @GETENT@
+GPERF = @GPERF@
 GREP = @GREP@
 HAVE_LIBGMP = @HAVE_LIBGMP@
 INSTALL = @INSTALL@
@@ -139,6 +146,7 @@ INSTALL_DATA = @INSTALL_DATA@
 INSTALL_PROGRAM = @INSTALL_PROGRAM@
 INSTALL_SCRIPT = @INSTALL_SCRIPT@
 INSTALL_STRIP_PROGRAM = @INSTALL_STRIP_PROGRAM@
+LCOV = @LCOV@
 LDFLAGS = @LDFLAGS@
 LIBBZ2 = @LIBBZ2@
 LIBBZ2_PREFIX = @LIBBZ2_PREFIX@
@@ -165,6 +173,7 @@ PACKAGE_STRING = @PACKAGE_STRING@
 PACKAGE_TARNAME = @PACKAGE_TARNAME@
 PACKAGE_VERSION = @PACKAGE_VERSION@
 PATH_SEPARATOR = @PATH_SEPARATOR@
+PKG_CONFIG = @PKG_CONFIG@
 RANLIB = @RANLIB@
 SED = @SED@
 SET_MAKE = @SET_MAKE@
@@ -244,6 +253,7 @@ top_srcdir = @top_srcdir@
 @BUILD_CLAMD_TRUE@@HAVE_MILTER_TRUE@man_MANS = $(top_builddir)/docs/man/clamav-milter.8
 AM_CPPFLAGS = -I$(top_srcdir)/clamd -I$(top_srcdir)/libclamav -I$(top_srcdir)/shared -I$(top_srcdir)
 EXTRA_DIST = clamav-milter.c INSTALL
+CLEANFILES = *.gcda *.gcno
 all: all-am
 
 .SUFFIXES:
@@ -305,6 +315,22 @@ clean-sbinPROGRAMS:
 	  echo " rm -f $$p $$f"; \
 	  rm -f $$p $$f ; \
 	done
+
+installcheck-sbinPROGRAMS: $(sbin_PROGRAMS)
+	bad=0; pid=$$$$; list="$(sbin_PROGRAMS)"; for p in $$list; do \
+	  case ' $(AM_INSTALLCHECK_STD_OPTIONS_EXEMPT) ' in \
+	   *" $$p "* | *" $(srcdir)/$$p "*) continue;; \
+	  esac; \
+	  f=`echo "$$p" | \
+	     sed 's,^.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/'`; \
+	  for opt in --help --version; do \
+	    if "$(DESTDIR)$(sbindir)/$$f" $$opt >c$${pid}_.out \
+	         2>c$${pid}_.err </dev/null \
+		 && test -n "`cat c$${pid}_.out`" \
+		 && test -z "`cat c$${pid}_.err`"; then :; \
+	    else echo "$$f does not support $$opt" 1>&2; bad=1; fi; \
+	  done; \
+	done; rm -f c$${pid}_.???; exit $$bad
 clamav-milter$(EXEEXT): $(clamav_milter_OBJECTS) $(clamav_milter_DEPENDENCIES) 
 	@rm -f clamav-milter$(EXEEXT)
 	$(LINK) $(clamav_milter_OBJECTS) $(clamav_milter_LDADD) $(LIBS)
@@ -561,6 +587,7 @@ install-strip:
 mostlyclean-generic:
 
 clean-generic:
+	-test -z "$(CLEANFILES)" || rm -f $(CLEANFILES)
 
 distclean-generic:
 	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
@@ -605,7 +632,7 @@ install-pdf: install-pdf-am
 
 install-ps: install-ps-am
 
-installcheck-am:
+installcheck-am: installcheck-sbinPROGRAMS
 
 maintainer-clean: maintainer-clean-am
 	-rm -rf ./$(DEPDIR)
@@ -640,11 +667,11 @@ uninstall-man: uninstall-man8
 	install-html-am install-info install-info-am install-man \
 	install-man8 install-pdf install-pdf-am install-ps \
 	install-ps-am install-sbinPROGRAMS install-strip installcheck \
-	installcheck-am installdirs maintainer-clean \
-	maintainer-clean-generic mostlyclean mostlyclean-compile \
-	mostlyclean-generic mostlyclean-libtool pdf pdf-am ps ps-am \
-	tags uninstall uninstall-am uninstall-man uninstall-man8 \
-	uninstall-sbinPROGRAMS
+	installcheck-am installcheck-sbinPROGRAMS installdirs \
+	maintainer-clean maintainer-clean-generic mostlyclean \
+	mostlyclean-compile mostlyclean-generic mostlyclean-libtool \
+	pdf pdf-am ps ps-am tags uninstall uninstall-am uninstall-man \
+	uninstall-man8 uninstall-sbinPROGRAMS
 
 # Tell versions [3.59,3.63) of GNU make to not export all variables.
 # Otherwise a system limit (for SysV at least) may be exceeded.
